import { Button } from "@renderer/components/ui/button";
import { ScrollArea } from "@renderer/components/ui/scroll-area";
import { Separator } from "@renderer/components/ui/separator";
import type { SettingsState } from "@renderer/hooks/useSettingsState";
import { Loader2, RefreshCw } from "lucide-react";
import { useEffect } from "react";

interface AIContextSectionProps {
  claudeMdContent: string | null;
  claudeMdLoading: boolean;
  claudeMdError: boolean;
  loadClaudeMd: SettingsState["loadClaudeMd"];
  isActive: boolean;
}

export function AIContextSection({
  claudeMdContent,
  claudeMdLoading,
  claudeMdError,
  loadClaudeMd,
  isActive,
}: AIContextSectionProps) {
  useEffect(() => {
    if (isActive) loadClaudeMd();
  }, [isActive, loadClaudeMd]);

  return (
    <div className="space-y-0">
      <div className="flex items-center justify-between pb-3 pt-1">
        <div>
          <h3 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground/60">
            Server AI Context
          </h3>
          <p className="mt-1 text-[11px] text-muted-foreground">
            This file is auto-generated by myRP.build and read by the AI before every generation. It
            reflects your server's current configuration.
          </p>
        </div>
        <Button
          variant="ghost"
          size="sm"
          className="h-7 w-7 shrink-0 p-0"
          onClick={loadClaudeMd}
          disabled={claudeMdLoading}
        >
          <RefreshCw className={`size-3.5 ${claudeMdLoading ? "animate-spin" : ""}`} />
        </Button>
      </div>
      <Separator className="mb-3" />

      {claudeMdLoading ? (
        <div className="flex items-center gap-1.5 py-6 text-[11px] text-muted-foreground">
          <Loader2 className="size-3 animate-spin" />
          Loading AI context file...
        </div>
      ) : claudeMdError ? (
        <div className="rounded-md border border-border/60 bg-muted/30 px-4 py-6 text-center">
          <p className="text-xs text-muted-foreground">
            Not generated yet. Detect your server context first.
          </p>
        </div>
      ) : claudeMdContent !== null ? (
        <div className="rounded-md border border-border/60 bg-muted/30 overflow-hidden">
          <ScrollArea className="max-h-[60vh]">
            <pre className="p-4 font-mono text-[11px] leading-relaxed text-foreground/80 whitespace-pre-wrap break-words">
              {claudeMdContent}
            </pre>
          </ScrollArea>
        </div>
      ) : null}
    </div>
  );
}
