import { cpSync, existsSync, mkdirSync } from "node:fs";
import { cp, mkdir, readdir, readFile, rm, unlink, writeFile } from "node:fs/promises";
import { basename, join, relative, resolve } from "node:path";
import type {
  GenerationResult,
  ManifestSummary,
  ServerContext,
  WrittenFile,
} from "../renderer/src/lib/types";

interface GenerationManifest {
  resourceName: string;
  files: string[]; // absolute paths
  resourceDir: string;
  createdAt: string;
  /**
   * Pre-overwrite snapshot of the resource. Present only when
   * this generation overwrote an EXISTING resource; absent for brand-new ones.
   * undoGeneration restores from here so a regeneration is reversible.
   */
  backupPath?: string;
}

/**
 * Write a manifest tracking which files the agent wrote, for undo.
 * Returns the GenerationResult used by the UI.
 */
export async function writeGenerationManifest(
  localPath: string,
  resourceName: string,
  absolutePaths: string[],
  backupPath?: string,
): Promise<GenerationResult> {
  const resourceDir = resolve(localPath, resourceName);

  const manifest: GenerationManifest = {
    resourceName,
    files: absolutePaths,
    resourceDir,
    createdAt: new Date().toISOString(),
    ...(backupPath ? { backupPath } : {}),
  };

  const manifestPath = join(resourceDir, "generation-manifest.json");

  try {
    await mkdir(resourceDir, { recursive: true });
    await writeFile(manifestPath, JSON.stringify(manifest, null, 2), "utf-8");
  } catch {
    // Non-fatal — undo just won't work
  }

  const writtenFiles: WrittenFile[] = absolutePaths.map((abs) => ({
    absolutePath: abs,
    relativePath: relative(resourceDir, abs),
  }));

  return {
    resourceName,
    resourceDir,
    files: writtenFiles,
    manifestPath,
  };
}

/**
 * Synchronously snapshot an existing resource folder before it's overwritten
 * SYNC (cpSync) on purpose: it runs inside the streaming
 * onChunk handler on `tool-input-available` — i.e. BEFORE the agent's write_file
 * executes — and because the stream consumer calls onChunk synchronously, the
 * copy completes before the write lands. That makes the snapshot race-free.
 *
 * Returns the backup path (recorded in the manifest so undoGeneration can
 * restore it), or undefined if the resource doesn't exist or the copy fails
 * (non-fatal — a failed backup must never block generation).
 */
export function backupResourceSync(resourceDir: string, localPath: string): string | undefined {
  if (!existsSync(resourceDir)) return undefined; // brand-new resource — nothing to back up
  const resourceName = basename(resourceDir);
  const backupsDir = join(localPath, "..", ".myrpbuild", "backups");
  const backupPath = join(backupsDir, `${Date.now()}_${resourceName}`);
  try {
    mkdirSync(backupsDir, { recursive: true });
    cpSync(resourceDir, backupPath, { recursive: true });
    return backupPath;
  } catch {
    return undefined; // non-fatal
  }
}

/**
 * Append `ensure <resourceName>` to server.cfg if not already present.
 * Non-fatal — swallows all errors silently.
 */
export async function appendEnsureLine(serverCfgPath: string, resourceName: string): Promise<void> {
  try {
    const content = await readFile(serverCfgPath, "utf-8");
    const alreadyEnsured = content
      .split("\n")
      .some((line) => line.toLowerCase().includes(`ensure ${resourceName.toLowerCase()}`));
    if (!alreadyEnsured) {
      await writeFile(serverCfgPath, `${content}\nensure ${resourceName}`, "utf-8");
    }
  } catch {
    // Non-fatal
  }
}

/**
 * Write (or overwrite) a .claude/CLAUDE.md to the server root.
 * This file is read by the Agent SDK (settingSources: ['project'])
 * on every generation to provide server-specific context.
 * Fully managed by myRP.build — overwritten on every context scan.
 * DO NOT edit manually.
 */
export async function writeServerClaudeMd(
  serverPath: string,
  context: ServerContext,
  existingResources?: string[],
): Promise<void> {
  const claudeDir = join(serverPath, ".claude");
  const claudeMdPath = join(claudeDir, "CLAUDE.md");

  const resources = existingResources ?? context.existingResources ?? [];
  const resourceList =
    resources.length > 0 ? resources.map((r) => `- ${r}`).join("\n") : "- (none yet)";

  const content = `# FiveM Server Context
<!-- AUTO-GENERATED BY myRP.build — DO NOT EDIT -->
<!-- This file is overwritten on every context scan. Any manual changes will be lost. -->

## Server Identity
Framework: ${context.framework}
DB Driver: ${context.dbDriver}
Inventory: ${context.inventory}
Game Build: ${context.gameBuild !== "unknown" ? context.gameBuild : "unknown"}
Server Config: ${context.serverCfgPath}

## Known Resources
${resourceList}
`;

  try {
    await mkdir(claudeDir, { recursive: true });
    await writeFile(claudeMdPath, content, "utf-8");
  } catch {
    // Non-fatal — generation still works without it
  }
}

/**
 * Undo a generation: delete all files listed in the manifest,
 * then remove the resource directory entirely.
 */
export async function undoGeneration(manifestPath: string): Promise<void> {
  let manifest: GenerationManifest;

  try {
    const raw = await readFile(manifestPath, "utf-8");
    manifest = JSON.parse(raw) as GenerationManifest;
  } catch {
    throw new Error(`Could not read generation manifest at ${manifestPath}`);
  }

  for (const filePath of manifest.files) {
    try {
      await unlink(filePath);
    } catch {
      // already gone
    }
  }

  try {
    await unlink(manifestPath);
  } catch {}

  // Restore: if this generation overwrote an existing
  // resource, put the pre-overwrite snapshot back so undo truly reverses the
  // regeneration (not just deletes the new files). For a brand-new resource
  // (no backup) keep the original behavior — remove the directory.
  if (manifest.backupPath && existsSync(manifest.backupPath)) {
    try {
      await rm(manifest.resourceDir, { recursive: true, force: true });
      await cp(manifest.backupPath, manifest.resourceDir, { recursive: true });
      await rm(manifest.backupPath, { recursive: true, force: true });
    } catch {
      // best-effort restore — the snapshot stays in .myrpbuild/backups if it fails
    }
  } else {
    try {
      await rm(manifest.resourceDir, { recursive: true });
    } catch {
      // directory may have user-added files — leave it
    }
  }
}

export async function listGenerationManifests(localPath: string): Promise<ManifestSummary[]> {
  const summaries: ManifestSummary[] = [];
  try {
    const entries = await readdir(localPath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name.startsWith(".")) continue;
      const manifestPath = join(localPath, entry.name, "generation-manifest.json");
      try {
        const raw = await readFile(manifestPath, "utf-8");
        const manifest = JSON.parse(raw) as GenerationManifest;
        summaries.push({
          resourceName: manifest.resourceName,
          resourceDir: manifest.resourceDir,
          fileCount: manifest.files.length,
          createdAt: manifest.createdAt,
          manifestPath,
        });
      } catch {
        // corrupt or missing manifest — skip
      }
    }
  } catch {
    return [];
  }
  summaries.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  return summaries;
}

export async function removeEnsureLine(serverCfgPath: string, resourceName: string): Promise<void> {
  try {
    const content = await readFile(serverCfgPath, "utf-8");
    const filtered = content
      .split("\n")
      .filter(
        (line) => !line.trim().toLowerCase().startsWith(`ensure ${resourceName.toLowerCase()}`),
      )
      .join("\n");
    await writeFile(serverCfgPath, filtered, "utf-8");
  } catch {
    // Non-fatal
  }
}

export async function isEnsured(serverCfgPath: string, resourceName: string): Promise<boolean> {
  try {
    const content = await readFile(serverCfgPath, "utf-8");
    return content
      .split("\n")
      .some((line) => line.trim().toLowerCase().startsWith(`ensure ${resourceName.toLowerCase()}`));
  } catch {
    return false;
  }
}
