/**
 * New-server scaffolder (multi-server epic, fivem-studio-m8se.4).
 *
 * Creates a fresh server folder: starter server.cfg + resources/[local] +
 * resources/[ox], with the ox base (ox_lib, oxmysql, ox_core, ox_inventory)
 * downloaded and wired into the cfg. The ox download is BEST-EFFORT — the folder
 * is always scaffolded; any resource that fails to download is reported so the
 * user (or the agent's install_resource) can add it later.
 *
 * NOTE: avoid ';' in server.cfg comments — FiveM splits a line on ';' before
 * honoring it, so a commented ';' would truncate the line (reference: vault
 * fivem-cfg-no-semicolons-in-comments).
 */
import { access, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import log from "electron-log/main";
import type { ScaffoldResult } from "../renderer/src/lib/types";
import { downloadAndExtractOx, OX_BASE } from "./ox-releases";

export type { ScaffoldResult };

/** Filesystem-safe folder name from a user-entered server name. */
export function sanitizeServerFolderName(name: string): string {
  const cleaned = name
    .trim()
    .replace(/[<>:"/\\|?*]+/g, "") // strip path-illegal chars
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^[-.]+|[-.]+$/g, "");
  return cleaned || "fivem-server";
}

/** A sensible starter ox server.cfg (no ';' in comments — see file header). */
export function starterServerCfg(name: string): string {
  const hostname = name.trim() || "My ox server";
  return `# Generated by myRP.build — starter ox_overextended server
# Fill in the placeholders marked CHANGE_ME before going live

endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

sv_maxclients 48
sv_hostname "${hostname}"
sv_licenseKey "CHANGE_ME"
rcon_password "CHANGE_ME"

# OneSync + game build (b3095 recommended for current ox)
set onesync on
sv_enforceGameBuild 3095

# Database — oxmysql connection string (CHANGE_ME)
set mysql_connection_string "mysql://user:password@localhost/fivem?charset=utf8mb4"

# ox base — load order matters (lib then mysql then core then inventory)
ensure ox_lib
ensure oxmysql
ensure ox_core
ensure ox_inventory

# Your resources live in resources/[local]
# ensure your_resource_here
`;
}

/**
 * Scaffold a new server folder under `parentDir` named `name`. Refuses if the
 * target folder already exists (no overwrite). Downloads the ox base best-effort.
 */
export async function scaffoldServer(parentDir: string, name: string): Promise<ScaffoldResult> {
  const serverPath = join(parentDir, sanitizeServerFolderName(name));

  // No-overwrite: refuse an existing folder so we never clobber a server.
  try {
    await access(serverPath);
    throw new Error(`A folder already exists at ${serverPath}. Pick a different name or location.`);
  } catch (err) {
    if (err instanceof Error && err.message.startsWith("A folder already exists")) throw err;
    // ENOENT — good, the folder is free.
  }

  const oxDir = join(serverPath, "resources", "[ox]");
  await mkdir(join(serverPath, "resources", "[local]"), { recursive: true });
  await mkdir(oxDir, { recursive: true });

  const serverCfgPath = join(serverPath, "server.cfg");
  await writeFile(serverCfgPath, starterServerCfg(name), "utf-8");

  // Best-effort ox base — keep going if any single resource fails.
  const installed: string[] = [];
  const failed: string[] = [];
  for (const resource of OX_BASE) {
    try {
      await downloadAndExtractOx(resource, oxDir);
      installed.push(resource);
    } catch (err) {
      log.warn(`[scaffold] failed to download ${resource}:`, err);
      failed.push(resource);
    }
  }

  return { serverPath, serverCfgPath, installed, failed };
}
