/**
 * Server backup to GitHub — repo init + .gitignore (fivem-studio-1yef.1).
 *
 * git (NOT Dolt — Dolt is beads-internal only) for a server FOLDER's files +
 * history. Distinct from the local auto-backup/undo (fileWriter) and from the
 * game-DB backup. This module owns the FOUNDATION step: make a server folder a git
 * repo (if it isn't already) and write a FiveM-appropriate .gitignore, plus flag
 * likely secrets in server.cfg so the user scrubs them BEFORE the first push
 * (connect-remote + commit/push are 1yef.2/.3). All git runs via execFile (no
 * shell) against the server folder.
 */
import { execFile } from "node:child_process";
import { access, readFile, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

// Force token-only auth for network git ops. Without this, Windows Git Credential
// Manager intercepts the push/clone, ignores the token embedded in the URL, and
// pops a GUI GitHub login that HANGS the child process. Disabling the credential
// helper + forbidding interactive prompts makes git use only the in-URL token and
// fail FAST (a clean, scrubbed error) if it's wrong — no popup, no hang.
const NO_PROMPT_ARGS = ["-c", "credential.helper=", "-c", "credential.interactive=false"];
function noPromptEnv(): NodeJS.ProcessEnv {
  return { ...process.env, GIT_TERMINAL_PROMPT: "0", GCM_INTERACTIVE: "never" };
}

/** FiveM server .gitignore — exclude runtime caches, logs, artifacts, OS noise.
 *  server.cfg is intentionally NOT ignored (load order is worth versioning); its
 *  secrets are surfaced via scanServerCfgSecrets instead. */
export const FIVEM_GITIGNORE = `# Server backup .gitignore — generated by myRP.build (fivem-studio-1yef)
# Runtime caches & artifacts (regenerated by FXServer / txAdmin)
cache/
**/cache/
*.log
logs/
crashes/

# myRP.build runtime wrapper (auto-deploy)
myrp-fxserver-loop.bat

# OS / editor noise
.DS_Store
Thumbs.db
node_modules/
`;

/** A server.cfg line whose value is likely a secret (key/line only — never the value). */
export interface SecretWarning {
  line: number;
  directive: string;
}

export interface GitInitResult {
  ok: boolean;
  /** The folder was already a git repo (init skipped). */
  alreadyRepo: boolean;
  /** A .gitignore was created (an existing one is never clobbered). */
  gitignoreWritten: boolean;
  /** Likely-secret lines in server.cfg to scrub before pushing publicly. */
  secretWarnings: SecretWarning[];
  error?: string;
}

/** Named FiveM secret directives + a generic `set <name>(key|token|secret|password)`. */
const SECRET_DIRECTIVE =
  /\b(sv_licenseKey|steam_webApiKey|rcon_password|mysql_connection_string)\b/i;
const SECRET_SET = /^set\s+(\S*(?:key|token|secret|password|licen[sc]e))\b/i;

/** Scan a server folder's server.cfg for likely secrets (returns keys/lines, never values). */
export async function scanServerCfgSecrets(serverPath: string): Promise<SecretWarning[]> {
  let text: string;
  try {
    text = await readFile(join(serverPath, "server.cfg"), "utf8");
  } catch {
    return []; // no server.cfg at the folder root — nothing to flag
  }
  const out: SecretWarning[] = [];
  text.split(/\r?\n/).forEach((raw, i) => {
    const line = raw.trim();
    if (!line || line.startsWith("#")) return;
    const named = line.match(SECRET_DIRECTIVE);
    const generic = line.match(SECRET_SET);
    const directive = named?.[1] ?? generic?.[1];
    if (directive) out.push({ line: i + 1, directive });
  });
  return out;
}

// ── GitHub remote: account + repo + git remote (fivem-studio-1yef.2) ─────────
// The per-user GitHub OAuth token is obtained via Supabase linkIdentity in the
// renderer (provider_token) and handed to main, which stores it in safeStorage
// (NEVER the database). These helpers use it to verify the account, create/link
// ONE repo per server, and point the server folder's `origin` at the repo. The
// remote stored in .git/config is the CLEAN https url (no token) — the token is
// injected only at push time (1yef.3). Team sharing is GitHub-native (collaborator
// invites), so the repo URL is the only thing shared (via the cloud servers row).

const GITHUB_API = "https://api.github.com";

export interface GithubRepoInfo {
  fullName: string; // "owner/repo"
  cloneUrl: string; // https clone url (no credentials)
  htmlUrl: string;
  isPrivate: boolean;
}

interface GithubFetchInit {
  method?: string;
  body?: string;
}

async function githubFetch(token: string, path: string, init?: GithubFetchInit): Promise<Response> {
  return fetch(`${GITHUB_API}${path}`, {
    method: init?.method ?? "GET",
    body: init?.body,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "myRP.build",
      ...(init?.body ? { "Content-Type": "application/json" } : {}),
    },
  });
}

/** Verify a GitHub token and return the authenticated user's login. Throws on a
 *  bad/expired token (401) or other non-2xx. */
export async function getGithubLogin(token: string): Promise<string> {
  const res = await githubFetch(token, "/user");
  if (res.status === 401)
    throw new Error("GitHub token is invalid or was revoked. Reconnect GitHub.");
  if (!res.ok) throw new Error(`GitHub /user failed (${res.status})`);
  const json = (await res.json()) as { login?: string };
  if (!json.login) throw new Error("GitHub /user returned no login.");
  return json.login;
}

/** A valid GitHub repo name derived from a server folder name (alnum . _ - only). */
export function deriveRepoName(serverPath: string): string {
  const base = basename(serverPath)
    .replace(/[^a-zA-Z0-9._-]+/g, "-")
    .replace(/^[-.]+|[-.]+$/g, "")
    .slice(0, 90);
  return base || "fivem-server";
}

function toRepoInfo(json: {
  full_name: string;
  clone_url: string;
  html_url: string;
  private: boolean;
}): GithubRepoInfo {
  return {
    fullName: json.full_name,
    cloneUrl: json.clone_url,
    htmlUrl: json.html_url,
    isPrivate: json.private,
  };
}

/**
 * Ensure a repo exists for this server: return it if it already exists, else
 * create it (private by default). `org` creates under an organization; otherwise
 * it's the authenticated user's personal account.
 */
export async function ensureGithubRepo(
  token: string,
  opts: { name: string; owner: string; isPrivate?: boolean; org?: string },
): Promise<GithubRepoInfo> {
  const ownerForLookup = opts.org ?? opts.owner;
  const existing = await githubFetch(
    token,
    `/repos/${encodeURIComponent(ownerForLookup)}/${encodeURIComponent(opts.name)}`,
  );
  if (existing.ok) return toRepoInfo(await existing.json());
  if (existing.status !== 404) {
    throw new Error(`GitHub repo lookup failed (${existing.status})`);
  }
  // Create: POST /user/repos (personal) or /orgs/{org}/repos (organization).
  const created = await githubFetch(
    token,
    opts.org ? `/orgs/${encodeURIComponent(opts.org)}/repos` : "/user/repos",
    {
      method: "POST",
      body: JSON.stringify({ name: opts.name, private: opts.isPrivate ?? true, auto_init: false }),
    },
  );
  if (!created.ok) {
    const detail = await created.text().catch(() => "");
    throw new Error(`GitHub repo create failed (${created.status})${detail ? `: ${detail}` : ""}`);
  }
  return toRepoInfo(await created.json());
}

/** Point the server folder's `origin` at `url` (clean, token-free). Idempotent:
 *  adds the remote, or updates it if one already exists. */
export async function setGitRemote(serverPath: string, url: string): Promise<void> {
  try {
    await execFileAsync("git", ["remote", "add", "origin", url], { cwd: serverPath });
  } catch {
    // origin already exists — repoint it.
    await execFileAsync("git", ["remote", "set-url", "origin", url], { cwd: serverPath });
  }
}

/** The clean `origin` url for a server repo, or null if none/not a repo. */
export async function getGitRemoteUrl(serverPath: string): Promise<string | null> {
  try {
    const { stdout } = await execFileAsync("git", ["remote", "get-url", "origin"], {
      cwd: serverPath,
    });
    return stdout.trim() || null;
  } catch {
    return null;
  }
}

export interface CommitPushResult {
  ok: boolean;
  committed: boolean; // a new commit was created this run
  sha?: string; // short sha at HEAD after the run
  pushed: boolean;
  nothingToCommit?: boolean; // working tree was already clean
  error?: string;
}

/** Inject a GitHub token into a clean https remote for a one-shot push. The token
 *  is used only as a transient process arg — NEVER written to .git/config. */
function withToken(cleanUrl: string, token: string): string {
  return cleanUrl.replace(/^https:\/\//i, "https://x-access-token:" + token + "@");
}

/** Remove a token from a string before it's logged or surfaced (defense in depth:
 *  git can echo the remote — including embedded creds — in push errors). */
function scrubToken(s: string, token: string): string {
  return token ? s.split(token).join("***") : s;
}

/**
 * Commit the server folder (everything not .gitignored) and push it to `remoteUrl`
 * on `main`, authenticating with `token` at push time only. Idempotent: a clean
 * tree skips the commit and the push reports up-to-date. The token never lands in
 * .git/config (origin stays the clean url) and is scrubbed from any error.
 */
export async function commitAndPushServer(
  serverPath: string,
  opts: { token: string; login: string; remoteUrl: string; message?: string },
): Promise<CommitPushResult> {
  const { token, login, remoteUrl } = opts;
  try {
    if (!(await isGitRepo(serverPath))) {
      return {
        ok: false,
        committed: false,
        pushed: false,
        error: "Not a git repo — link a backup repo first.",
      };
    }
    await execFileAsync("git", ["add", "-A"], { cwd: serverPath });
    const { stdout: status } = await execFileAsync("git", ["status", "--porcelain"], {
      cwd: serverPath,
    });
    let committed = false;
    if (status.trim()) {
      const message = opts.message?.trim() || "myRP.build backup " + new Date().toISOString();
      // Per-commit identity so we don't depend on the user's global git config.
      await execFileAsync(
        "git",
        [
          "-c",
          "user.name=" + login,
          "-c",
          "user.email=" + login + "@users.noreply.github.com",
          "commit",
          "-m",
          message,
        ],
        { cwd: serverPath },
      );
      committed = true;
    }
    let sha: string | undefined;
    try {
      const { stdout } = await execFileAsync("git", ["rev-parse", "--short", "HEAD"], {
        cwd: serverPath,
      });
      sha = stdout.trim();
    } catch {
      // no commits yet (empty repo) — nothing to push
      return { ok: false, committed, pushed: false, error: "Nothing to back up yet." };
    }
    try {
      await execFileAsync(
        "git",
        [...NO_PROMPT_ARGS, "push", withToken(remoteUrl, token), "HEAD:main"],
        { cwd: serverPath, env: noPromptEnv() },
      );
    } catch (err) {
      return {
        ok: false,
        committed,
        sha,
        pushed: false,
        error: scrubToken(err instanceof Error ? err.message : String(err), token),
      };
    }
    return { ok: true, committed, sha, pushed: true, nothingToCommit: !committed };
  } catch (err) {
    return {
      ok: false,
      committed: false,
      pushed: false,
      error: scrubToken(err instanceof Error ? err.message : String(err), token),
    };
  }
}

/** Pure auto-backup eligibility gate (1yef/dbjw): enabled + connected + a repo
 *  linked. Kept here (no Electron deps) so it's unit-testable. */
export function autoBackupEligible(opts: {
  enabled?: boolean;
  serverPath?: string | null;
  token?: string | null;
  login?: string | null;
  remoteUrl?: string | null;
}): boolean {
  return !!(opts.enabled && opts.serverPath && opts.token && opts.login && opts.remoteUrl);
}

export interface RestoreResult {
  ok: boolean;
  localPath?: string;
  error?: string;
}

/** The repo name (folder name) for a clone, derived from its https url. */
function repoNameFromUrl(remoteUrl: string): string {
  return (remoteUrl.split("/").pop() || "server").replace(/\.git$/i, "") || "server";
}

/**
 * Clone a backed-up server repo into `parentDir/<repoName>` (1yef.4). The token
 * authenticates the clone (private repos) but is then stripped: origin is reset to
 * the clean url so no credential persists in .git/config. Refuses to overwrite an
 * existing folder; the token is scrubbed from any error.
 *
 * NOTE: gitignored files (e.g. the externalized `myrp-secrets.cfg`) are NOT in the
 * repo, so a restored server is missing its secrets until the user re-adds them.
 */
export async function cloneServerRepo(opts: {
  token: string;
  remoteUrl: string;
  parentDir: string;
}): Promise<RestoreResult> {
  const { token, remoteUrl, parentDir } = opts;
  const dest = join(parentDir, repoNameFromUrl(remoteUrl));
  try {
    if (await fileExists(dest)) {
      return { ok: false, error: `A folder named "${basename(dest)}" already exists there.` };
    }
    await execFileAsync("git", [...NO_PROMPT_ARGS, "clone", withToken(remoteUrl, token), dest], {
      env: noPromptEnv(),
    });
    // Strip the token: leave origin as the clean url (matches the backup path).
    await execFileAsync("git", ["remote", "set-url", "origin", remoteUrl], { cwd: dest });
    return { ok: true, localPath: dest };
  } catch (err) {
    return {
      ok: false,
      error: scrubToken(err instanceof Error ? err.message : String(err), token),
    };
  }
}

async function isGitRepo(dir: string): Promise<boolean> {
  try {
    await access(join(dir, ".git"));
    return true;
  } catch {
    return false;
  }
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Initialize a server folder as a git repo (idempotent) and ensure a sensible
 * .gitignore exists. Re-running on an existing repo just tops up the .gitignore
 * (never clobbering a user's own) and re-scans for secrets.
 */
export async function gitInitServer(serverPath: string): Promise<GitInitResult> {
  try {
    const alreadyRepo = await isGitRepo(serverPath);
    if (!alreadyRepo) {
      // -b main sets the initial branch (git >= 2.28; the app ships modern git).
      await execFileAsync("git", ["init", "-b", "main"], { cwd: serverPath });
    }
    const gitignorePath = join(serverPath, ".gitignore");
    let gitignoreWritten = false;
    if (!(await fileExists(gitignorePath))) {
      await writeFile(gitignorePath, FIVEM_GITIGNORE, "utf8");
      gitignoreWritten = true;
    }
    const secretWarnings = await scanServerCfgSecrets(serverPath);
    return { ok: true, alreadyRepo, gitignoreWritten, secretWarnings };
  } catch (err) {
    return {
      ok: false,
      alreadyRepo: false,
      gitignoreWritten: false,
      secretWarnings: [],
      error: err instanceof Error ? err.message : String(err),
    };
  }
}
